#!/usr/bin/env python
import re,sys,os,json,urllib2,urllib,argparse,random
def main(args):
    num = 0
    if args.random:
        num = random.randint(0,15)
    
    home_dir = os.path.expanduser('~')
    dest_dir=home_dir+'/Pictures/bing/'
    
    if not os.path.exists(dest_dir):
        os.mkdir(dest_dir)
    
    if args.verbose:
        print 'Requesting and Parsing JSON'
    try:
        src_json = urllib2.urlopen('http://www.bing.com/HPImageArchive.aspx?format=js&idx=%d&n=1&mkt=en-US'%(num)).read()
    except  Exception as ex:
        print ex
        sys.exit(1)

    src = json.loads(src_json)
    
    if args.verbose:
        print 'Extracting img url from Bing-JSON API'
    
    link = src['images'][0]['url']
    info = src['images'][0]['copyright']
    if not args.quiet:
        print 'Image description: '+ info
    
    if args.verbose:
        print 'Renaming Image'
    
    img = re.search(r'\/az\/hprichbg\/rb\/(\w+)_EN\S+(\.jpg|png|tiff|jpeg|gif)',link)
    img_name= img.group(1)+img.group(2)
    
    idx = os.path.join(dest_dir+img_name)
    
    if args.verbose:
        print 'Checking if Image already there in Folder'
    
    if not os.path.exists(idx):
        if args.verbose:
            print 'Downloading the image...'
        urllib.urlretrieve('https://bing.com'+link,idx)
    
    if args.verbose:
        print 'Setting the Image......'
    
    os.system("gsettings set org.gnome.desktop.background picture-uri file://%s"%(idx))
    
    if args.verbose:
        print 'Done!' 
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Extracting Random Bing Images')
    exgroup = parser.add_mutually_exclusive_group()
    parser.add_argument('-r','--random',action='store_true',help='Random image selection from last 15 days')
    exgroup.add_argument('-v','--verbose',action='store_true',help='To Show Downloading and Setting Process')
    exgroup.add_argument('-q','--quiet',action='store_true',help='Do not display anything on Terminal')
    args = parser.parse_args()
    main(args)
