#!/usr/bin/env python
import sys,argparse
def isprime(x):
    if x<=1:
        return False
    if x==2 or x == 3:
        return True
    if x%2 == 0 or x%3 == 0:
        return False
    for i in xrange(3,int(x**0.5)+2,2):
        if x%i == 0:
            return False
    return True

# execute expression e.g 12*4+55-7
def default (expr):
    return eval(expr)
def main(args):
    if args.expr:
        print default(' '.join(args.expr))
    elif args.isprime:
        if isprime(args.isprime[0]):
            var = 'a'
        else:
            var = 'not' 
        print args.isprime,'is',var,'Prime Number'
    
if __name__=='__main__':
    parser=argparse.ArgumentParser(description='A Script to For basic Calculation like finding a prime number,evaulting a mathematical expression')
    parser.add_argument('-isp','--isprime',nargs=1,type=int,help='check if given number is prime or not')
    parser.add_argument('-e','--expr',nargs='+',type=str,help='evaluate the expression')
    args = parser.parse_args()
    main(args)
